baseURL = 'https://carve-wiki.netlify.app'
languageCode = 'ja'
title = 'FUN CARVE Wiki'
unsafe = true

[module]                                
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]

BookTheme = 'auto'

BookRepo = 'https://github.com/nick-san/carve-wiki'

BookDateFormat = '2006, Jan 2'

ResourceURL = "https://carvewikicontents.blob.core.windows.net/"

[caches]
  [caches.getresource]
    dir = ':cacheDir/:project'
    maxAge = 1

[security]
  enableInlineShortcodes = true
  
  [security.http]
    methods = ['GET']
    urls = ['.*']

  [security.funcs]
    getenv = ['^HUGO_', '^MICROCMS_']

[resources]
  [resources.getRemote]
    timeout = '30s'
