baseURL = 'https://nick-san.github.io/carve-wiki/'
languageCode = 'ja'
title = 'FUN CARVE Wiki'
unsafe = true

[module]                                
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

